[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = min_spiffs.csv
build_flags = 
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=3
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.2
    bblanchon/ArduinoJson @ ^7.0.4
    https://github.com/tzapu/WiFiManager.git#v2.0.17
